-- ==================================================
-- Smart Tourism & Heritage Management Platform
-- Oracle Database Schema
-- Run this as / connected to the TOURISM_APP user
-- ==================================================

-- Drop tables if they already exist (children first)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FEEDBACK CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EVENT_REGISTRATIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EVENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PAYMENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BOOKINGS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TOUR_GUIDES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ADMINS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TOURISTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE HERITAGE_SITES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ==================================================
-- USERS
-- ==================================================
CREATE TABLE USERS (
  USER_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME      VARCHAR2(150) NOT NULL,
  EMAIL     VARCHAR2(150) NOT NULL UNIQUE,
  PASSWORD  VARCHAR2(255) NOT NULL,
  PHONE     VARCHAR2(20),
  ROLE      VARCHAR2(20) NOT NULL CHECK (ROLE IN ('TOURIST', 'TOUR_GUIDE', 'ADMIN'))
);

-- ==================================================
-- TOURISTS
-- ==================================================
CREATE TABLE TOURISTS (
  TOURIST_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID     NUMBER NOT NULL UNIQUE,
  ADDRESS     VARCHAR2(255),
  AGE         NUMBER,
  GENDER      VARCHAR2(20),
  CONSTRAINT FK_TOURISTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- ==================================================
-- ADMINS
-- ==================================================
CREATE TABLE ADMINS (
  ADMIN_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID      NUMBER NOT NULL UNIQUE,
  DESIGNATION  VARCHAR2(150),
  CONSTRAINT FK_ADMINS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- ==================================================
-- TOUR_GUIDES
-- ==================================================
CREATE TABLE TOUR_GUIDES (
  GUIDE_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID       NUMBER NOT NULL UNIQUE,
  EXPERIENCE    NUMBER,
  LANGUAGE      VARCHAR2(255),
  AVAILABILITY  VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (AVAILABILITY IN ('AVAILABLE', 'UNAVAILABLE')),
  CONSTRAINT FK_GUIDES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- ==================================================
-- HERITAGE_SITES
-- ==================================================
CREATE TABLE HERITAGE_SITES (
  SITE_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SITE_NAME      VARCHAR2(200) NOT NULL,
  LOCATION       VARCHAR2(200) NOT NULL,
  DESCRIPTION    VARCHAR2(4000),
  OPENING_TIME   VARCHAR2(20),
  CLOSING_TIME   VARCHAR2(20),
  TICKET_PRICE   NUMBER(10, 2) DEFAULT 0
);

-- ==================================================
-- BOOKINGS
-- ==================================================
CREATE TABLE BOOKINGS (
  BOOKING_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TOURIST_ID        NUMBER NOT NULL,
  SITE_ID           NUMBER NOT NULL,
  GUIDE_ID          NUMBER NOT NULL,
  BOOKING_DATE      DATE DEFAULT SYSDATE,
  VISIT_DATE        DATE NOT NULL,
  NUMBER_OF_TICKETS NUMBER NOT NULL,
  BOOKING_STATUS    VARCHAR2(30) DEFAULT 'PENDING' CHECK (
    BOOKING_STATUS IN ('PENDING', 'ACCEPTED', 'REJECTED', 'PAYMENT_PROCESSING', 'CONFIRMED', 'CANCELLED')
  ),
  CONSTRAINT FK_BOOKINGS_TOURIST FOREIGN KEY (TOURIST_ID) REFERENCES TOURISTS(TOURIST_ID),
  CONSTRAINT FK_BOOKINGS_SITE FOREIGN KEY (SITE_ID) REFERENCES HERITAGE_SITES(SITE_ID),
  CONSTRAINT FK_BOOKINGS_GUIDE FOREIGN KEY (GUIDE_ID) REFERENCES TOUR_GUIDES(GUIDE_ID)
);

-- ==================================================
-- PAYMENTS
-- ==================================================
CREATE TABLE PAYMENTS (
  PAYMENT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BOOKING_ID      NUMBER NOT NULL UNIQUE,
  AMOUNT          NUMBER(10, 2) NOT NULL,
  PAYMENT_METHOD  VARCHAR2(30) CHECK (PAYMENT_METHOD IN ('UPI', 'CARD', 'NET_BANKING')),
  PAYMENT_STATUS  VARCHAR2(30) DEFAULT 'PENDING' CHECK (
    PAYMENT_STATUS IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED')
  ),
  PAYMENT_DATE    DATE,
  CONSTRAINT FK_PAYMENTS_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS(BOOKING_ID)
);

-- ==================================================
-- EVENTS
-- ==================================================
CREATE TABLE EVENTS (
  EVENT_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SITE_ID      NUMBER NOT NULL,
  EVENT_NAME   VARCHAR2(200) NOT NULL,
  EVENT_DATE   DATE NOT NULL,
  EVENT_TIME   VARCHAR2(20),
  DESCRIPTION  VARCHAR2(4000),
  CONSTRAINT FK_EVENTS_SITE FOREIGN KEY (SITE_ID) REFERENCES HERITAGE_SITES(SITE_ID)
);

-- ==================================================
-- EVENT_REGISTRATIONS
-- (needed to support "Tourist can register for events")
-- ==================================================
CREATE TABLE EVENT_REGISTRATIONS (
  REGISTRATION_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EVENT_ID            NUMBER NOT NULL,
  TOURIST_ID           NUMBER NOT NULL,
  REGISTRATION_DATE   DATE DEFAULT SYSDATE,
  CONSTRAINT FK_EVENTREG_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID),
  CONSTRAINT FK_EVENTREG_TOURIST FOREIGN KEY (TOURIST_ID) REFERENCES TOURISTS(TOURIST_ID),
  CONSTRAINT UQ_EVENTREG UNIQUE (EVENT_ID, TOURIST_ID)
);

-- ==================================================
-- FEEDBACK
-- ==================================================
CREATE TABLE FEEDBACK (
  FEEDBACK_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TOURIST_ID     NUMBER NOT NULL,
  SITE_ID        NUMBER NOT NULL,
  RATING         NUMBER(1) NOT NULL CHECK (RATING BETWEEN 1 AND 5),
  COMMENTS       VARCHAR2(4000),
  FEEDBACK_DATE  DATE DEFAULT SYSDATE,
  CONSTRAINT FK_FEEDBACK_TOURIST FOREIGN KEY (TOURIST_ID) REFERENCES TOURISTS(TOURIST_ID),
  CONSTRAINT FK_FEEDBACK_SITE FOREIGN KEY (SITE_ID) REFERENCES HERITAGE_SITES(SITE_ID)
);

COMMIT;
